name: ward.fisher
description: next generation
version: 0.0.1
author: tqgba2cp.kkcizzd5@t1h04srt.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: wardfisher
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2025-12-05 21:44:59'
pipelines:
  pipelines/Grant_SauerRay_GunnJunior_Lesch:
    name: Grant_SauerRay_GunnJunior_Lesch
    description: null
    author: tqgba2cp.kkcizzd5@t1h04srt.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-12-05 21:44:59'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-12-05 21:44:59'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-12-05T21:44:59.440494Z'
  name: plibMaven
  version: 8.16.0-SNAPSHOT
  id: '514136343'
  createdAt: '2025-12-05T21:44:59.440494Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
